FROM apache/airflow:2.10.5-python3.11

ARG AIRFLOW_VERSION=2.10.5
ARG PYTHON_VERSION=3.11

USER airflow
ENV PYTHONPATH=/opt/airflow/project

RUN pip install --no-cache-dir \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt" \
    yfinance==1.2.0 psycopg2-binary

COPY --chown=airflow:root etl /opt/airflow/project/etl